services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5046:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_CHAT_HUB_URL: http://localhost:5046/chatHub
    ports:
      - "5173:80"
    depends_on:
      - backend
